import { TEMPLATE_LIBRARY_SLUGS } from './constants';

export interface TemplateDefinition {
  slug: string;
  name: string;
  summary: string;
  persona: string;
  category: string;
  sampleUseCase: string;
  cta: string;
  isInteractive: boolean;
}

const definitions: Record<string, Omit<TemplateDefinition, 'slug'>> = {
  'growth-engine-builder': {
    name: 'Growth Engine Builder',
    summary: 'Design your full-funnel growth machine with conversion targets per stage.',
    persona: 'CRO / Growth Lead',
    category: 'Revenue',
    sampleUseCase: 'Map acquisition channels, activation tactics, and retention programs with owned metrics.',
    cta: 'Launch Builder',
    isInteractive: true,
  },
  'cashflow-waterfall': {
    name: 'Cashflow Waterfall',
    summary: 'Plan runway and capital deployment with variance analysis.',
    persona: 'CFO / COO',
    category: 'Finance',
    sampleUseCase: 'Model revenue recognition vs. expenses and scenario plan hiring classes.',
    cta: 'Model Cashflow',
    isInteractive: true,
  },
  'expense-ratio-analyzer': {
    name: 'Expense Ratio Analyzer',
    summary: 'Track spend ratios across departments and benchmark efficiency.',
    persona: 'Finance Lead',
    category: 'Finance',
    sampleUseCase: 'Compare GTM, R&D, and G&A ratios quarter over quarter.',
    cta: 'Analyze Ratios',
    isInteractive: false,
  },
  'twelve-quarter-planning': {
    name: '12Q Planning Canvas',
    summary: 'Align on rolling 3-year priorities, KPIs, and investment bets.',
    persona: 'CEO / Chief of Staff',
    category: 'Strategy',
    sampleUseCase: 'Set annual targets, strategic pillars, and supporting initiatives.',
    cta: 'Start Planning',
    isInteractive: false,
  },
  'incentivewise-planner': {
    name: 'IncentiveWise Planner',
    summary: 'Design compensation programs tied to leading indicators.',
    persona: 'People Ops',
    category: 'People',
    sampleUseCase: 'Draft spiffs and bonuses mapped to OKRs.',
    cta: 'Design Incentives',
    isInteractive: false,
  },
  'clarity-compass': {
    name: 'Clarity Compass',
    summary: 'Set narrative, positioning, and proof points for leadership storytelling.',
    persona: 'CEO',
    category: 'Narrative',
    sampleUseCase: 'Prepare board materials with consistent messaging.',
    cta: 'Craft Narrative',
    isInteractive: false,
  },
  'hiring-scorecard': {
    name: 'Hiring Scorecard',
    summary: 'Standardize hiring criteria and feedback loops.',
    persona: 'Talent Lead',
    category: 'People',
    sampleUseCase: 'Collaborate on role scorecards with interview panels.',
    cta: 'Build Scorecard',
    isInteractive: false,
  },
  'customer-success-playbook': {
    name: 'Customer Success Playbook',
    summary: 'Codify lifecycle stages and success plans.',
    persona: 'CS Lead',
    category: 'Customer',
    sampleUseCase: 'Outline engagement cadence, health scoring, and renewal plays.',
    cta: 'Launch Playbook',
    isInteractive: false,
  },
  'sales-forecast-tracker': {
    name: 'Sales Forecast Tracker',
    summary: 'Track pipeline health and forecast accuracy.',
    persona: 'Sales Ops',
    category: 'Revenue',
    sampleUseCase: 'Monitor commit vs. upside by segment.',
    cta: 'Track Forecast',
    isInteractive: false,
  },
  'product-roadmap-navigator': {
    name: 'Product Roadmap Navigator',
    summary: 'Prioritize roadmap themes with impact scoring.',
    persona: 'CPO',
    category: 'Product',
    sampleUseCase: 'Sequence releases against capacity and customer impact.',
    cta: 'Plan Roadmap',
    isInteractive: false,
  },
  'market-expansion-matrix': {
    name: 'Market Expansion Matrix',
    summary: 'Evaluate new markets and GTM motions.',
    persona: 'Strategy',
    category: 'Strategy',
    sampleUseCase: 'Score market entries by TAM, CAC, and operational fit.',
    cta: 'Assess Markets',
    isInteractive: false,
  },
  'team-health-radar': {
    name: 'Team Health Radar',
    summary: 'Pulse check engagement and capacity across teams.',
    persona: 'People Ops',
    category: 'People',
    sampleUseCase: 'Collect feedback and escalate blockers quickly.',
    cta: 'Launch Radar',
    isInteractive: false,
  },
  'profitability-pulse': {
    name: 'Profitability Pulse',
    summary: 'Monitor gross margin and payback period trends.',
    persona: 'Finance',
    category: 'Finance',
    sampleUseCase: 'Identify efficiency gains by segment.',
    cta: 'Check Pulse',
    isInteractive: false,
  },
  'operating-rhythm-planner': {
    name: 'Operating Rhythm Planner',
    summary: 'Define cadences for leadership and team meetings.',
    persona: 'Chief of Staff',
    category: 'Operations',
    sampleUseCase: 'Assign owners, agendas, and follow-ups for key rituals.',
    cta: 'Plan Rhythm',
    isInteractive: false,
  },
  'board-update-template': {
    name: 'Board Update Template',
    summary: 'Package KPIs, highlights, and asks for board reviews.',
    persona: 'CEO',
    category: 'Narrative',
    sampleUseCase: 'Automate board-ready reporting with commentary.',
    cta: 'Compose Update',
    isInteractive: false,
  },
  'capital-allocation-planner': {
    name: 'Capital Allocation Planner',
    summary: 'Model investment priorities and cash deployment.',
    persona: 'Finance',
    category: 'Finance',
    sampleUseCase: 'Weigh growth bets vs. efficiency initiatives.',
    cta: 'Allocate Capital',
    isInteractive: false,
  },
  'pipeline-quality-audit': {
    name: 'Pipeline Quality Audit',
    summary: 'Audit deal hygiene and progression bottlenecks.',
    persona: 'Sales Ops',
    category: 'Revenue',
    sampleUseCase: 'Score opportunities across stages and segments.',
    cta: 'Audit Pipeline',
    isInteractive: false,
  },
  'retention-signal-monitor': {
    name: 'Retention Signal Monitor',
    summary: 'Track health scores, usage, and expansion signals.',
    persona: 'CS Ops',
    category: 'Customer',
    sampleUseCase: 'Route alerts to owners with ready-made plays.',
    cta: 'Monitor Signals',
    isInteractive: false,
  },
  'scenario-lab': {
    name: 'Scenario Lab',
    summary: 'Run what-if models across revenue, cash, and hiring.',
    persona: 'Finance',
    category: 'Finance',
    sampleUseCase: 'Queue scenarios and compare to baseline projections.',
    cta: 'Open Scenario Lab',
    isInteractive: false,
  },
  'north-star-tracker': {
    name: 'North Star Tracker',
    summary: 'Align teams on the primary metric and contributing drivers.',
    persona: 'CEO / Product',
    category: 'Strategy',
    sampleUseCase: 'Cascade goals into KPIs and templates.',
    cta: 'Track Progress',
    isInteractive: false,
  },
};

export const TEMPLATE_LIBRARY: TemplateDefinition[] = TEMPLATE_LIBRARY_SLUGS.map((slug) => ({
  slug,
  ...definitions[slug],
}));
